# Generated by Django 5.0.7 on 2024-11-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softarinapp', '0003_servicesdescript2_delete_servicesdescript'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_uk', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_es', models.CharField(db_index=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_uk', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='stages_images/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
